const comicsData = [
  {
    id: "001",
    title: "The Dark Sentinel: Origins",
    price: 14.99,
    publisher: "Marvel Comics",
    genre: "Superhero",
    releaseDate: "2024-01-15",
    description: "Witness the birth of a legend! When scientist Marcus Stone is exposed to cosmic radiation, he gains extraordinary powers but must face the darkness within. A thrilling origin story that redefines what it means to be a hero.",
    coverImage: "assets/comic-001.jpg",
    pages: 32,
    writer: "Sarah Chen",
    artist: "Miguel Rodriguez"
  },
  {
    id: "002",
    title: "Quantum Rebels Vol. 1",
    price: 19.99,
    publisher: "DC Comics",
    genre: "Sci-Fi",
    releaseDate: "2024-02-20",
    description: "In a dystopian future where time travel is controlled by mega-corporations, a band of rebels must steal quantum technology to save their timeline. Action-packed adventures across multiple dimensions!",
    coverImage: "assets/comic-002.jpg",
    pages: 48,
    writer: "James Park",
    artist: "Elena Volkov"
  },
  {
    id: "003",
    title: "Mystic Chronicles: The Awakening",
    price: 16.99,
    publisher: "Image Comics",
    genre: "Fantasy",
    releaseDate: "2024-03-10",
    description: "When ancient magic returns to the modern world, young librarian Emma discovers she's the last in a line of powerful sorcerers. Dark forces are rising, and only she can stop them.",
    coverImage: "assets/comic-003.jpg",
    pages: 36,
    writer: "Rachel Morrison",
    artist: "Kai Tanaka"
  },
  {
    id: "004",
    title: "Street Justice #12",
    price: 12.99,
    publisher: "Marvel Comics",
    genre: "Action",
    releaseDate: "2024-01-25",
    description: "The streets run red as the vigilante known only as Havoc takes on the city's most dangerous crime syndicate. High-octane action meets gritty storytelling in this explosive issue!",
    coverImage: "assets/comic-004.jpg",
    pages: 28,
    writer: "Marcus Williams",
    artist: "Sofia Martinez"
  },
  {
    id: "005",
    title: "Galactic Guardians: Infinity War",
    price: 21.99,
    publisher: "DC Comics",
    genre: "Sci-Fi",
    releaseDate: "2024-02-05",
    description: "The fate of the universe hangs in the balance as the Galactic Guardians face their greatest threat yet. An ancient evil awakens, and heroes from across the cosmos must unite or fall.",
    coverImage: "assets/comic-005.jpg",
    pages: 52,
    writer: "David Chen",
    artist: "Yuki Nakamura"
  },
  {
    id: "006",
    title: "The Phantom Detective #5",
    price: 13.99,
    publisher: "Dark Horse Comics",
    genre: "Mystery",
    releaseDate: "2024-03-15",
    description: "In the shadows of Victorian London, the Phantom Detective solves crimes that Scotland Yard won't touch. A murdered aristocrat, stolen artifacts, and a conspiracy that reaches the throne itself.",
    coverImage: "assets/comic-006.jpg",
    pages: 32,
    writer: "Elizabeth Blackwood",
    artist: "Thomas Sterling"
  },
  {
    id: "007",
    title: "Neon Samurai",
    price: 17.99,
    publisher: "Image Comics",
    genre: "Action",
    releaseDate: "2024-01-30",
    description: "In a cyberpunk Tokyo, the last samurai wields both ancient blade and cutting-edge technology. When his clan is betrayed, he must navigate a world of corporate espionage and cyber-warfare to reclaim his honor.",
    coverImage: "assets/comic-007.jpg",
    pages: 40,
    writer: "Hiroshi Yamamoto",
    artist: "Alex Chen"
  },
  {
    id: "008",
    title: "The Crimson Witch Chronicles",
    price: 15.99,
    publisher: "Marvel Comics",
    genre: "Fantasy",
    releaseDate: "2024-02-28",
    description: "Scarlet magic and dark prophecies collide! The Crimson Witch must gather the lost artifacts of power before her nemesis opens a portal to the demon realm. The fate of two worlds hangs by a thread.",
    coverImage: "assets/comic-008.jpg",
    pages: 36,
    writer: "Amanda Foster",
    artist: "Isabella Romano"
  },
  {
    id: "009",
    title: "Zombie Apocalypse: Patient Zero",
    price: 18.99,
    publisher: "Dark Horse Comics",
    genre: "Horror",
    releaseDate: "2024-03-20",
    description: "The outbreak begins. Follow the harrowing journey of Dr. Sarah Collins as she races to find the source of the infection while the world crumbles around her. Horror and humanity in equal measure.",
    coverImage: "assets/comic-009.jpg",
    pages: 44,
    writer: "Robert King",
    artist: "Maria Santos"
  },
  {
    id: "010",
    title: "Thunder Force United",
    price: 16.99,
    publisher: "DC Comics",
    genre: "Superhero",
    releaseDate: "2024-01-08",
    description: "When Earth faces invasion from the Void Dimension, heroes must set aside their differences and unite! Thunder Force assembles the planet's mightiest champions for an epic battle that will reshape the DC Universe!",
    coverImage: "assets/comic-010.jpg",
    pages: 48,
    writer: "Christopher Lane",
    artist: "Diana Cruz"
  },
  {
    id: "011",
    title: "Legends of Asgard",
    price: 19.99,
    publisher: "Marvel Comics",
    genre: "Fantasy",
    releaseDate: "2024-02-14",
    description: "Journey to the realm of gods and monsters! Ancient Norse mythology comes alive as Thor faces betrayal from within Asgard's golden halls. Epic battles and legendary quests await!",
    coverImage: "assets/comic-011.jpg",
    pages: 40,
    writer: "Erik Thorson",
    artist: "Freya Anderson"
  },
  {
    id: "012",
    title: "Cyber Noir: Hard Reset",
    price: 14.99,
    publisher: "Image Comics",
    genre: "Sci-Fi",
    releaseDate: "2024-03-05",
    description: "In a rain-soaked megacity where memories can be bought and sold, detective Jack Cipher investigates a murder that never happened. Neo-noir meets cyberpunk in this mind-bending thriller.",
    coverImage: "assets/comic-012.jpg",
    pages: 36,
    writer: "Vincent Noir",
    artist: "Luna Park"
  },
  {
    id: "013",
    title: "The Savage Lands",
    price: 13.99,
    publisher: "Dark Horse Comics",
    genre: "Adventure",
    releaseDate: "2024-01-18",
    description: "Lost in a prehistoric world filled with dinosaurs and danger, a team of explorers must survive against impossible odds. Think Jurassic Park meets Lost World in this thrilling adventure series!",
    coverImage: "assets/comic-013.jpg",
    pages: 32,
    writer: "Jake Hunter",
    artist: "Rex Stone"
  },
  {
    id: "014",
    title: "Shadow Protocol",
    price: 15.99,
    publisher: "DC Comics",
    genre: "Mystery",
    releaseDate: "2024-02-22",
    description: "A top-secret government agency. A conspiracy that goes all the way to the top. Agent Maya Cross must expose the truth before she becomes the next target. Trust no one.",
    coverImage: "assets/comic-014.jpg",
    pages: 36,
    writer: "Patricia Grey",
    artist: "Marcus Black"
  },
  {
    id: "015",
    title: "Dragon's Fury",
    price: 17.99,
    publisher: "Image Comics",
    genre: "Fantasy",
    releaseDate: "2024-03-12",
    description: "When dragons return to a world that thought them extinct, kingdoms fall and new alliances form. Young dragon rider Kira must master her bond with the ancient fire-drake or watch her homeland burn.",
    coverImage: "assets/comic-015.jpg",
    pages: 44,
    writer: "Morgan Drake",
    artist: "Ember Phoenix"
  },
  {
    id: "016",
    title: "Speedster: Velocity",
    price: 12.99,
    publisher: "Marvel Comics",
    genre: "Superhero",
    releaseDate: "2024-01-22",
    description: "The fastest hero alive faces his greatest challenge yet when a villain from the future arrives to erase him from the timeline. A race against time itself in this high-speed adventure!",
    coverImage: "assets/comic-016.jpg",
    pages: 28,
    writer: "Ryan Flash",
    artist: "Zoom Martinez"
  },
  {
    id: "017",
    title: "Haunted House Chronicles",
    price: 16.99,
    publisher: "Dark Horse Comics",
    genre: "Horror",
    releaseDate: "2024-02-18",
    description: "They say the Blackwood Estate is cursed. When paranormal investigators enter its halls, they discover horrors beyond imagination. Some doors should never be opened.",
    coverImage: "assets/comic-017.jpg",
    pages: 40,
    writer: "Edgar Blackwood",
    artist: "Raven Darkmore"
  },
  {
    id: "018",
    title: "Space Rangers: Beyond the Void",
    price: 20.99,
    publisher: "DC Comics",
    genre: "Sci-Fi",
    releaseDate: "2024-03-08",
    description: "On the edge of known space, the Space Rangers patrol the cosmic frontier. When a distress signal leads them to a derelict alien vessel, they uncover a threat that could end all life in the galaxy.",
    coverImage: "assets/comic-018.jpg",
    pages: 48,
    writer: "Stella Nova",
    artist: "Orion Star"
  },
  {
    id: "019",
    title: "Martial Arts Master",
    price: 14.99,
    publisher: "Image Comics",
    genre: "Action",
    releaseDate: "2024-01-12",
    description: "Trained in twelve fighting styles, Master Li must defend his dojo from a ruthless crime boss who wants the ancient scrolls hidden in its walls. Breathtaking fight choreography in comic form!",
    coverImage: "assets/comic-019.jpg",
    pages: 32,
    writer: "Li Chen",
    artist: "Bruce Fang"
  },
  {
    id: "020",
    title: "The Last Kingdom",
    price: 18.99,
    publisher: "Marvel Comics",
    genre: "Fantasy",
    releaseDate: "2024-02-11",
    description: "In a world where magic is dying, the Last Kingdom stands as humanity's final bastion against the encroaching darkness. Prince Aldric must find the legendary Sunstone or watch his kingdom fall into eternal night.",
    coverImage: "assets/comic-020.jpg",
    pages: 44,
    writer: "George R. Stone",
    artist: "Arthur Pendragon"
  },
  {
    id: "021",
    title: "Noir City: Rain of Blood",
    price: 15.99,
    publisher: "Dark Horse Comics",
    genre: "Mystery",
    releaseDate: "2024-03-25",
    description: "Private eye Danny Cross takes on a case that leads him into the heart of the city's underworld. Femme fatales, corrupt cops, and a murder mystery that just won't quit. Classic noir at its finest.",
    coverImage: "assets/comic-021.jpg",
    pages: 36,
    writer: "Raymond Cross",
    artist: "Veronica Lake"
  },
  {
    id: "022",
    title: "Infinity Gauntlet: Endgame",
    price: 22.99,
    publisher: "Marvel Comics",
    genre: "Superhero",
    releaseDate: "2024-02-01",
    description: "The ultimate showdown! Earth's mightiest heroes unite for one final battle against the mad titan Thanos. Reality itself hangs in the balance in this epic crossover event!",
    coverImage: "assets/comic-022.jpg",
    pages: 56,
    writer: "Jim Starlin Jr.",
    artist: "Jack Kirby II"
  },
  {
    id: "023",
    title: "Steampunk Revolution",
    price: 17.99,
    publisher: "Image Comics",
    genre: "Adventure",
    releaseDate: "2024-03-18",
    description: "Victorian England meets mad science! Inventor Amelia Gearhart leads a revolution against the oppressive Steam Lords with her army of mechanical marvels. Gears, goggles, and glory!",
    coverImage: "assets/comic-023.jpg",
    pages: 40,
    writer: "Jules Verne Jr.",
    artist: "Cog Wheelman"
  },
  {
    id: "024",
    title: "The Necromancer's Apprentice",
    price: 16.99,
    publisher: "DC Comics",
    genre: "Horror",
    releaseDate: "2024-01-28",
    description: "When young apprentice Mordecai accidentally raises an army of the dead, he must learn to control his dark powers before they consume him. Dark magic and darker consequences await.",
    coverImage: "assets/comic-024.jpg",
    pages: 36,
    writer: "H.P. Grimwood",
    artist: "Morte Skulls"
  }
];
